sudo: required
services: 
  - docker

before_install:
  - docker build -t 546268815/react-node -f Dockerfile.dev .

script:
  - docker run -e CI=true 546268815/react-node npm run test -- --watchAll=false
